### ISSUE TITLE
Voting page is not responsive 

### ISSUE THREAD

**Issue by TheKatze** [Gabsii/spoti-vote#27] opened 2018-04-11 07:28 UTC
Describe your problem.
The Spoti-Vote voting room is unusable on mobile devices. Consider a vertical alignment of the voting options.

Can it be reprodueced? 
Just resize your browser to a smaller size or open spoti-vote on a mobile device.

Where did the error occur? 
Voting room on small sized browsers

**Comment by Gabsii** [comment] 2018-05-11 13:32
The problem is fixed in the current version! Thank you for your submission.

**Closed by Gabsii** 2018-05-11 13:32 UTC
Labels: enhancement
